/* Creación de usuario si está trabajando con BD Oracle XE */
CREATE USER PRY2205_S8 
IDENTIFIED BY "PRY2205.semana_8" 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

ALTER USER PRY2205_S8 QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO PRY2205_S8;

GRANT "RESOURCE" TO PRY2205_S8;

ALTER USER PRY2205_S8 DEFAULT ROLE "RESOURCE";




/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER PRY2205_S8 
IDENTIFIED BY "PRY2205.semana_8"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";

ALTER USER PRY2205_S8 QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION TO PRY2205_S8;

GRANT "RESOURCE" TO PRY2205_S8;

ALTER USER PRY2205_S8 DEFAULT ROLE "RESOURCE";


CREATE USER PRY2205_USER1 
IDENTIFIED BY "PRY2205.semana_8"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";

ALTER USER PRY2205_S8 QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION TO PRY2205_USER1;

GRANT "RESOURCE" TO PRY2205_USER1;

ALTER USER PRY2205_USER1 DEFAULT ROLE "RESOURCE";

CREATE USER PRY2205_USER2 
IDENTIFIED BY "PRY2205.semana_8"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";

ALTER USER PRY2205_S8 QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION TO PRY2205_USER2;

GRANT SELECT ON MEDICO TO PRY2205_USER2;
GRANT SELECT ON CARGO TO PRY2205_USER2;
GRANT SELECT ON UNIDAD_CONSULTA TO PRY2205_USER2;



-- USER SQL
ALTER USER "PRY2205_USER1"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER "PRY2205_USER1" QUOTA UNLIMITED ON "DATA";

-- ROLES
ALTER USER "PRY2205_USER1" DEFAULT ROLE "CONSOLE_OPERATOR";


-- USER SQL
ALTER USER "PRY2205_USER2"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS

-- ROLES
ALTER USER "PRY2205_USER2" DEFAULT ROLE "PRY2205_ROL_D";


--  SINONIMOS PUBLICOS

  CREATE  PUBLIC SYNONYM "PAGOS_PACIENTES" FOR "MODDATOS"."PAGOS";
  CREATE  PUBLIC SYNONYM "PAGOS_CESFAM" FOR "MODDATOS"."PACIENTE";
  
  -- SINONIMOS PRIVADOS
  
    CREATE   SYNONYM "PAGOS_PACIENTES" FOR "MODDATOS"."PAGOS";
    CREATE   SYNONYM "PAGOS_CESFAM" FOR "MODDATOS"."PACIENTE";
    

--ROLES

CREATE ROLE PRY2205_ROL_D;
GRANT SELECT ON MEDICO TO PRY2205_ROL_D;
GRANT SELECT ON CARGO TO PRY2205_ROL_D;
GRANT SELECT ON UNIDAD_CONSULTA TO PRY2205_ROL_D;

GRANT PRY2205_ROL_D TO PRY2205_USER1;

CREATE ROLE PRY2205_ROL_P;
GRANT PROCEDURE TO PRY2205_ROL_P;

GRANT PRY2205_ROL_P TO PRY2205_USER1;
GRANT PRY2205_ROL_P TO PRY2205_USER2;